### ISSUE TITLE
E a revalidação

### ISSUE THREAD

**Issue by EduOliveira1983** [tiagopariz/DomainNotification#1]
E ai Tiago, tudo bem?
Num cenário em que eu tenha que alterar um estado do objeto, eu teria que limpar a lista de erros antes de validar? 
Essa seria a melhor prática?
Seria algo do tipo um método chamando List.Clear somente ou a abordagem deveria ser outra?

**Comment by tiagopariz** [comment]
Segundo o Open-Close do SOLID, depois de criado, o estado do objeto não deve ser alterado. Mas eu criei um exemplo melhor elaborado no repositório [DesignByContract](https://github.com/tiagopariz/DesignByContract), onde uso esta abordagem para criar um validação de objeto.

Limpar a lista de erros, vai depender da tua regra de negócio, que inclusive envolve usar ou não princípios baseado no SOLID e DDD.

**Comment by bease** [comment]
> Limpar a lista de erros, vai depender da tua regra de negócio, que inclusive envolve usar ou não princípios baseado no SOLID e DDD.

No caso, eu gostaria sim de me basear no SOLID e no DDD, por isso que eu estou tentando ver qual é a melhor abordagem...
Pelo que entendi, então a cada alteração eu precisaria ter uma nova instancia do objeto, é isso?
(OBS: Desculpe-me se estiver perguntando/discutindo no lugar errado)

**Comment by tiagopariz** [comment]
Isto mesmo, até recomendo o vídeo do @EduardoPires sobre SOLID:

https://www.youtube.com/watch?v=Q2QdkiX6p_Y
